APT::FTPArchive::Release::Origin "Elyra";
APT::FTPArchive::Release::Label "Elyra";
APT::FTPArchive::Release::Suite "stable";
APT::FTPArchive::Release::Codename "stable";
APT::FTPArchive::Release::Architectures "amd64";
APT::FTPArchive::Release::Components "main";
APT::FTPArchive::Release::Description "Elyra Linux package repository";
